StockSim/StockSim

- .github/PULL_REQUEST_TEMPLATE.md
- docs/CHANGELOG.md
- docs/GitHub Workflow.md
Create pull request template.
Create documentation for Github workflow.
> ci: Create pull request template and Github workflow

- README.md
- docs/CHANGELOG.md
> docs: added use case 4 and 5

- docs/CHANGELOG.md
- src/main/java/data_access/IStockDataAccess.java
- src/main/java/entity/Stock.java
- src/main/java/entity/StockMarket.java
- src/main/java/entity/UserStock.java
Implement entities for `StockMarket`, `Stock`, `UserStock`.
Implement data access interface for accessing stock information API.
> feat: Implement Stock market entity

- docs/CHANGELOG.md
- src/main/java/entity/Portfolio.java
Modify Portfolio constructor to fit the new return value Optional<Stock> of StockMarket.getStock()
> fix: fix Portfolio constructor

- docs/CHANGELOG.md
- src/main/java/entity/Portfolio.java
> Portfolio constructor refactor

- docs/CHANGELOG.md
- src/main/java/app/AppBuilder.java
- src/main/java/app/Main.java
- src/main/java/data_access/IStockDataAccess.java
- src/main/java/entity/Portfolio.java
- src/main/java/entity/StockMarket.java
- src/main/java/entity/Transaction.java
- src/main/java/entity/UserStock.java
- src/main/java/interface_adapter/ViewManagerModel.java
- src/main/java/interface_adapter/ViewModel.java
- src/main/java/interface_adapter/execute_buy/ExecuteBuyController.java
- src/main/java/interface_adapter/execute_buy/ExecuteBuyPresenter.java
- src/main/java/interface_adapter/execute_buy/ExecuteBuyState.java
- src/main/java/interface_adapter/execute_buy/ExecuteBuyViewModel.java
- src/main/java/use_case/execute_buy/ExecuteBuyDataAccess.java
- src/main/java/use_case/execute_buy/ExecuteBuyInputBoundary.java
- src/main/java/use_case/execute_buy/ExecuteBuyInputData.java
- src/main/java/use_case/execute_buy/ExecuteBuyInteractor.java
- src/main/java/use_case/execute_buy/ExecuteBuyOutputBoundary.java
- src/main/java/use_case/execute_buy/ExecuteBuyOutputData.java
- src/main/java/use_case/session/SessionService.java
- src/main/java/view/BuyView.java
- src/main/java/view/ViewManager.java
Implement framework classes for buy stock use case.
Implement validation for invalid buy execution.
> feat: Partially Implement buy stock use case

- README.md
> docs: add use cases and user stories

- docs/CHANGELOG.md
- pom.xml
- src/main/java/data_access/InMemoryUserDataAccessObject.java
- src/main/java/entity/Portfolio.java
- src/main/java/entity/User.java
- src/main/java/entity/UserFactory.java
- src/main/java/entity/UserStock.java
- src/main/java/interface_adapter/execute_buy/ExecuteBuyController.java
- src/main/java/interface_adapter/execute_buy/ExecuteBuyPresenter.java
- src/main/java/use_case/execute_buy/ExecuteBuyDataAccess.java
- src/main/java/use_case/execute_buy/ExecuteBuyDataAccessInterface.java
- src/main/java/use_case/execute_buy/ExecuteBuyInputData.java
- src/main/java/use_case/execute_buy/ExecuteBuyInteractor.java
- src/main/java/use_case/execute_buy/ExecuteBuyOutputData.java
- src/main/java/view/GUI/MarketSearchPanel.java
- src/main/java/view/GUI/OrderEntryPanel.java
- src/main/java/view/GUI/PortfolioPanel.java
- src/main/java/view/GUI/TotalAssetsPanel.java
- src/test/java/use_case/execute_buy/ExecuteBuyInteractorTest.java
1. implemented the interactor
2. implemented unit test for interactor
> feat: implement execute_buy interactor and set up test

- docs/CHANGELOG.md
- src/main/java/data_access/InMemoryUserDataAccessObject.java
- src/main/java/interface_adapter/execute_buy/ExecuteBuyPresenter.java
- src/main/java/use_case/execute_buy/ExecuteBuyInteractor.java
- src/test/java/use_case/execute_buy/ExecuteBuyInteractorTest.java
Resolve errors caused by changes in output data class and output presenter interface.
> fix: Remove outdated classes and methods

- README.md
- src/main/java/entity/Portfolio.java
- src/main/java/entity/StockMarket.java
- src/main/java/session/SessionManager.java
- src/main/java/use_case/execute_buy/ExecuteBuyInteractor.java
- src/main/java/use_case/execute_buy/ExecuteBuyOutputData.java
- src/main/java/view/IComponent.java
- src/main/java/view/ViewBase.java
- src/main/java/view/ViewManager.java
- src/main/java/view/gui_components/display_info/AssetPanel.java
- src/main/java/view/gui_components/display_info/PortfolioPanel.java
> chores: add tasks for new features and enhancements

- src/main/java/entity/TransactionHistory.java
- src/main/java/use_case/execute_buy/ExecuteBuyInputData.java
- src/main/java/use_case/execute_buy/ExecuteBuyInteractor.java
- src/main/java/use_case/execute_buy/ExecuteBuyOutputData.java
> 3.1 add Javadoc to entities and the execute buy use case

- docs/CHANGELOG.md
- src/main/java/data_access/InMemoryStockDataAccessObject.java
- src/main/java/data_access/StockDataAccessObject.java
- src/main/java/entity/Stock.java
- src/main/java/entity/StockMarket.java
- src/test/java/use_case/execute_buy/ExecuteBuyInteractorTest.java
Added additional api calls to retrieve ticker's company name and industry. Modified Stock entity to store company and industry as well.
> feat: implemented company name and industry api data retrieval 

- docs/Team Collaboration.md
> docs: add team contribution doc

- docs/Documentation Requirements
> Create Documentation Requirements

- docs/CHANGELOG.md
- src/main/java/entity/Stock.java
- src/main/java/use_case/login/LoginInputBoundary.java
- src/main/java/use_case/login/LoginInteractor.java
- src/main/java/utility/ConfigLoader.java
- src/main/java/utility/MarketTracker.java
- src/main/java/utility/MarketTrackerConfigLoader.java
- src/main/java/utility/ServiceManager.java
- src/main/resources/config/market-tracker-config.txt
- src/test/java/use_case/login/LoginInteractorTest.java
Create `ConfigLoader` class to load static configuration.
Remove `async/await` implementation in `LoginInteractor`.
> refactor: fix comments for pull request #71

- docs/CHANGELOG.md
- src/main/java/data_access/DatabaseUserDataAccessObject.java
- src/main/java/data_access/InMemoryUserDataAccessObject.java
- src/main/java/entity/User.java
- src/main/java/interface_adapter/execute_buy/ExecuteBuyPresenter.java
- src/main/java/interface_adapter/view_history/ViewHistoryPresenter.java
- src/main/java/use_case/execute_buy/ExecuteBuyDataAccessInterface.java
- src/main/java/use_case/execute_buy/ExecuteBuyInteractor.java
- src/main/java/use_case/execute_buy/ExecuteBuyOutputBoundary.java
- src/main/java/use_case/login/LoginDataAccessInterface.java
- src/main/java/use_case/registration/RegistrationDataAccessInterface.java
- src/main/java/use_case/registration/RegistrationInteractor.java
- src/main/java/utility/MongoDBDocumentParser.java
- src/main/java/utility/MongoDBUserDocumentParser.java
- src/main/java/utility/data_transfer/PortfolioDTO.java
- src/main/java/utility/data_transfer/StockDTO.java
- src/main/java/utility/data_transfer/TransactionDTO.java
- src/main/java/utility/data_transfer/TransactionHistoryDTO.java
- src/main/java/utility/data_transfer/UserDTO.java
- src/main/java/utility/data_transfer/UserMapper.java
- src/main/java/utility/data_transfer/UserStockDTO.java
- src/test/java/use_case/registration/RegistrationInteractorTest.java
- Implement writing to database for execute buy use case.
- Create DTO objects for database data transfer.
- Fix issues with Document parsing.
> feat: implement writing to database for execute buy use case

- docs/CHANGELOG.md
- src/main/java/view/components/InputComponent.java
- src/main/java/view/panels/LogInPanel.java
- src/main/java/view/panels/OrderEntryPanel.java
- src/main/java/view/panels/SignUpPanel.java
> fix: all input fields should be cleared after use case

- .gitignore
- pom.xml
- src/main/java/data_access/DatabaseUserDataAccessObject.java
- src/main/java/data_access/InMemoryUserDataAccessObject.java
This version also adds spotless plugin without running it once.
Optimize gitignore file since we're ignoring whole .idea directory.
> fix: data access interfaces not registered

- docs/CHANGELOG.md
- src/main/java/utility/MarketTracker.java
Implement asynchronous stock data update in `updateStocks` method to prevent blocking the program during stock update.
> feat: Optimize stock update in `MarketTracker`

- .github/workflows/format-prettier.yml
- .github/workflows/format-spotless.yml
- .prettierrc
- docs/CHANGELOG.md
- src/main/java/interface_adapter/view_history/ViewHistoryPresenter.java
- src/main/java/view/panels/MarketSearchPanel.java
- src/main/java/view/panels/PortfolioPanel.java
- src/main/java/view/panels/TransactionHistoryPanel.java
Allowed numeric columns in tables from `MarketSearchPanel`, `PortfolioPanel`, and `TransactionHistoryPanel` to be sorted numerically instead of alphabetically.
> feat: implemented numeric sorting for tables

- README.md
- docs/Project Overview.md
> docs: refine readme
